config/routes.rb
Estudiuni::Application.routes.draw do
  root :to => 'home#index'
  
  namespace :admin do
    
    get '', :controller => 'admin', :action => 'login'
    get 'admin/login', :controller => 'admin', :action => 'login'
    post 'admin/login', :controller => 'admin', :action => 'login'  
    get 'admin/logout', :controller => 'admin', :action => 'logout'
    
    resources :main
    
    resources :designers
    
    resources :jobs do
      resources :job_images
      get 'job_images/:id/up', :controller => 'job_images', :action => 'up'
      get 'job_images/:id/down', :controller => 'job_images', :action => 'down'
    end
    
    resources :for_sale_items do
      resources :for_sale_item_images
      get 'for_sale_images/:id/up', :controller => 'for_sale_item_images', :action => 'up'
      get 'for_sale_images/:id/down', :controller => 'for_sale_item_images', :action => 'down'
    end
    
  end
  
  get '/about', :controller => 'main', :action => 'about'
  get '/jobs', :controller => 'main', :action => 'jobs'
  
  resources :home, only: [:index]
  resources :for_sale_items
  resources :contacts, only: [:index], :path => 'contact'
  
  get 'locales/:locale', :controller => 'locales', :action => 'set'
  
  get 'designers', :controller => 'designers', :action => 'index'
  get ':id', :controller => 'designers', :action => 'show'
  get ':designer_id/jobs', :controller => 'jobs', :action => 'index'
  get ':designer_id/sale', :controller => 'for_sale_items', :action => 'index'
  #get ':designer_id/jobs/:id', :controller => 'jobs', :action => 'show'
  
  get 'sale/:id', :controller => 'for_sale_items', :action => 'show'
  #get ':designer_id/shop/:id', :controller => 'jobs', :action => 'show'
  
  resources :jobs
  resources :designers
  resources :for_sale_items
  
end

app/models/designer.rb
class Designer < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  mount_uploader :image, ProfilePictureUploader
  mount_uploader :curriculum, CurriculumUploader
  
  default_scope :order => "name ASC"
  
  translates :about
  accepts_nested_attributes_for :translations
  
  attr_accessible :name, :surname, :about, :facebook, :blogger, :behance, :pinterest, :vimeo, :linkedin, 
                  :email, :image, :curriculum, :translations_attributes
  
  has_and_belongs_to_many :jobs
  has_many :for_sale_items
end

app/models/for_sale_item.rb
class ForSaleItem < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
  
  mount_uploader :cover, JobCoverUploader
  
  translates :description, :name
  accepts_nested_attributes_for :translations
  
  attr_accessible :name, :description, :cover, :designer_id, :translations_attributes
  
  belongs_to :designer
  has_many :for_sale_item_images
end

app/models/for_sale_item_image.rb
class ForSaleItemImage < ActiveRecord::Base
  mount_uploader :url, JobImageUploader
  
  default_scope :order => "position ASC"
  
  attr_accessible :url, :for_sale_item_id
  
  belongs_to :for_sale_item
  
  def self.consolidate_positions(for_sale_item_id)
    images = ForSaleItemImage.where("for_sale_item_id = ?", for_sale_item_id)
    position = 0
    images.each do |image|
      image.position = position
      image.save
      position = position + 1
    end    
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
  
  mount_uploader :cover, JobCoverUploader
  
  translates :description, :name
  accepts_nested_attributes_for :translations
  
  attr_accessible :name, :month, :year, :description, :cover, :designer_ids,
                  :featured, :translations_attributes
  
  has_and_belongs_to_many :designers
  has_many :job_images
  belongs_to :main
end

app/models/job_image.rb
class JobImage < ActiveRecord::Base
  mount_uploader :url, JobImageUploader
  
  default_scope :order => "position ASC"
  
  attr_accessible :url, :job_id
  
  belongs_to :job
  
  def self.consolidate_positions(job_id)
    images = JobImage.where("job_id = ?", job_id)
    position = 0
    images.each do |image|
      image.position = position
      image.save
      position = position + 1
    end    
  
  end
end

app/models/main.rb
class Main < ActiveRecord::Base
  mount_uploader :picture, ProfilePictureUploader
  
  translates :about
  accepts_nested_attributes_for :translations
  
  attr_accessible :about, :email, :picture, :translations_attributes
  
  has_many :jobs
end

app/controllers/admin/for_sale_items_controller.rb
class Admin::ForSaleItemsController < Admin::AdminController
  
  before_filter :authenticate
  
  def index
    @for_sale_items = ForSaleItem.all
  end

  def new
    @for_sale_item = ForSaleItem.new
    
    respond_to do |format|
      format.html #new.html.erb
    end
  end
  
  def create
    @for_sale_item = ForSaleItem.create( params[:for_sale_item] )
    
    respond_to do |format|
      if @for_sale_item.save
        format.html { redirect_to(:action => "index")}
      else
        format.html { redirect_to(:action => "new")}
      end
    end
  end

  def edit
    @for_sale_item = ForSaleItem.find( params[:id] )
  end

  def update
    @for_sale_item = ForSaleItem.find( params[:id] )
    @for_sale_item.update_attributes( params[:for_sale_item] )
    
    respond_to do |format|
      format.html { redirect_to(:action => "index") }
    end
  end
  
  def destroy
    for_sale_item = ForSaleItem.find( params[:id] )
    for_sale_item.delete
    
    respond_to do |format|
      format.html { redirect_to(:action => "index") }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @designers = Designer.all
  end
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
  
  def index
    @designers = Designer.all
  end
  
  def show
    @designer = Designer.find( params[:id] )
  end
end

app/controllers/for_sale_items_controller.rb
class ForSaleItemsController < ApplicationController
  def index
    @designer = Designer.find( params[:designer_id] )
  end
  
  def show
    @for_sale_item = ForSaleItem.find( params[:id] )
    
    if request.path != for_sale_item_path(@for_sale_item)
      redirect_to @for_sale_item, status: :moved_permanently
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @jobs = Job.where("featured = 1").order("RAND()").limit(10)
  end
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  
  def index
    @designer = Designer.find( params[:designer_id] )
  end
  
  def show
    @job = Job.find( params[:id] )
    
    if I18n.locale.to_s == "pt"
      @months = ["JANEIRO", "FEVEREIRO", "MARÇO", "ABRIL", "MAIO", "JUNHO", "JULHO", "AGOSTO",
                  "SETEMBRO", "OUTUBRO", "NOVEMBRO", "DEZEMBRO"]
    elsif I18n.locale.to_s == "en"
      @months = ["JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST",
                "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"]
    end
      
    if request.path != job_path(@job)
      redirect_to @job, status: :moved_permanently
    end
  end
end

app/controllers/locales_controller.rb
class LocalesController < ApplicationController
  
  def set
    if (params[:locale] == "pt")
      session[:locale] = I18n.locale = :pt
    elsif (params[:locale] == "en")
      session[:locale] = I18n.locale = :en
    end
    render :json => { :status => :ok }
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  def about
    @estudiuni = Main.first
  end
  
  def jobs
    @estudiuni = Main.first
    @jobs = Job.all
  end
end

app/helpers/admin/for_sale_items_helper.rb
module Admin::ForSaleItemsHelper
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/admin/main_helper.rb
module Admin::MainHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/helpers/for_sale_items_helper.rb
module ForSaleItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/admin/for_sale_items/_form.html.erb
<%= form_for [:admin, @for_sale_item] do |f| %>
	<% if @for_sale_item.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@for_sale_item.errors.count, "error") %> prohibited this job from being saved:</h2>
			
			<ul>
				<% @for_sale_item.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<div class="field">
		<%= f.label "Nome" %><br />
		<%= f.text_field :name %>
	</div>
	
	<div class="field">
		<%= f.label "Descrição" %><br />
		<%= f.text_area :description, :class => "tinymce", :rows => 10, :cols => 80 %>
	</div>
	
	<%= f.globalize_fields_for :en do |g| %>
	<div class="field">
		<%= g.label "Nome (Inglês)" %><br />
		<%= g.text_field :name %>
	</div>
	
	<div class="field">
		<%= g.label "Descrição (Inglês)" %><br />
		<%= g.text_area :description, :class => "tinymce", :rows => 10, :cols => 80 %>
	</div>
	<% end %>
	
	<div class="field">
		<%= f.label "Capa" %>
		<%= f.file_field :cover %>
	</div>
	
	<div class="field">
		<%= f.label "Designer" %>
		<%= f.select :designer_id, options_from_collection_for_select(Designer.all, "id", "name"),
			:prompt => "Escolha um designer" %>
	</div>
	
	<script type="text/javascript">
		tinymce.init({
		    mode: 'textareas',
		    theme: 'advanced',
		    plugins : "paste",
		    theme_advanced_buttons3_add : "pastetext,pasteword,selectall",
		    paste_auto_cleanup_on_paste : true
		});
	</script> 
	
	<div class="action">
		<%= f.submit @submit_text %>
	</div>
<% end %>

app/views/admin/for_sale_items/edit.html.erb
<%= content_for :sidebar do %>
	<ul class="sideNav">
		<li><%= link_to "Editar Imagens", admin_for_sale_item_for_sale_item_images_path(@for_sale_item.id) %>
		</li>
	</ul>
<% end %>

<%= content_for :breadcrumbs do %>
	<h2>
		<%= link_to "Trabalhos", admin_for_sale_items_path %>&raquo;
		<a href="#" class="active">Editar trabalho</a>
	</h2>
<% end %>

<% @submit_text = "Atualizar" %>
<%= render "form" %>

app/views/admin/for_sale_items/index.html.erb
<%= content_for :breadcrumbs do %>
	<h2><a href="#" class="active">Itens à venda</a></h2>
<% end %>

<%= link_to "Novo trabalho", new_admin_for_sale_item_path, :class => "button" %>

<table class="admin_content">
	<tr>
		<th class="first">Nome</th>
		<th>Capa</th>
		<th class="last"></th>
	</tr>
	<% isOdd = false %>
	<% @for_sale_items.each do |for_sale_item| %>
		<tr class="<%= isOdd ? "odd" : "" %>">
			<td class="first"><%= for_sale_item.name %></td>
			<td><%= for_sale_item.cover.thumb.blank? ? "" : image_tag(for_sale_item.cover.small_thumb) %></td>
			<td class="last">
				<%= link_to "Editar", edit_admin_for_sale_item_path(for_sale_item.id) %>
				<%= link_to "Deletar", admin_for_sale_item_path(for_sale_item.id), 
	    			:method => :delete, data: { confirm: 'Você tem certeza de que deseja deletar este trabalho?' } %>
			</td>		
		</tr>
	<% isOdd = !isOdd %>
	<% end %>
</table>

<%= link_to "Novo trabalho", new_admin_for_sale_item_path, :class => "button" %>

app/views/admin/for_sale_items/new.html.erb
<%= content_for :breadcrumbs do %>
	<h2>
		<%= link_to "Trabalhos", admin_for_sale_items_path %>&raquo;
		<a href="#" class="active">Novo trabalho</a>
	</h2>
<% end %>

<% @submit_text = "Salvar" %>
<%= render "form" %>

app/views/for_sale_items/index.html.erb
<%= stylesheet_link_tag "artist" %>

<section id="profile">
	<%= image_tag @designer.image, :class => "avatar" %>
	<p><a href="mailto:<%= @designer.email%>"><%= @designer.email%></a></p>
	<ul class="social-media">
		<li class="social <%= @designer.facebook.blank? ? "hide" : "facebook" %>">
			<a href="<%= @designer.facebook %>" target="_blank"></a>
		</li>
		<li class="social <%= @designer.behance.blank? ? "hide" : "behance" %>">
			<a href="<%= @designer.behance %>" target="_blank"></a>
		</li>
		<li class="social <%= @designer.linkedin.blank? ? "hide" : "linkedin" %>">
			<a href="<%= @designer.linkedin %>" target="_blank"></a>
		</li>
		<li class="social <%= @designer.vimeo.blank? ? "hide" : "vimeo" %>">
			<a href="<%= @designer.vimeo %>" target="_blank"></a>
		</li>
		<li class="social <%= @designer.pinterest.blank? ? "hide" : "pinterest" %>">
			<a href="<%= @designer.pinterest %>" target="_blank"></a>
		</li>
		<li class="social <%= @designer.blogger.blank? ? "hide" : "blogger" %>">
			<a href="<%= @designer.blogger %>" target="_blank"></a>
		</li>
	</ul>
</section>

<section id="artist-content" class="shop">
	<h1><%= @designer.name.to_s + " " + @designer.surname.to_s %></h1>
	<ul id="tabs">
		<li id="about"><%= link_to (t :about).upcase, 
				{:controller => "designers", :action => "show", :id => @designer}%></li>
		<li id="jobs"><%= link_to (t :jobs).upcase, 
				{:controller => "jobs", :action => "index", :designer_id => @designer}%></li>
		<li id="shop"><a href="#"><%= (t :shop).upcase %></a></li>
		
	</ul>
	<ul id="artist-works">
	<% @designer.for_sale_items.each do |item| %>
		<li>
			<%= link_to image_tag(item.cover.thumb),
				{ :controller => "for_sale_items", :action => "show", :id => item } %>
			<%= link_to item.name,
				{ :controller => "for_sale_items", :action => "show", :id => item }, :class => "title" %>
		</li>
	<% end %>		
	</ul>
</section>

app/views/for_sale_items/show.html.erb
<%= stylesheet_link_tag "works" %>
<%= javascript_include_tag "work" %>

<h1><%= @for_sale_item.name %></h1>

<section id="images">
	<ul id="gallery">
		<% left = true %>
		<% index = 1 %>
		<% @for_sale_item.for_sale_item_images.each do |image| %>
			<li class="<%= left ? "left" : "right" %>" data-index="<%= index %>"><%= image_tag image.url.thumb %></li>
			<% left = !left %>
			<% index += 1 %>
		<% end %>
		</ul>
		
	<div id="showcase">
		<%= image_tag "arrow_left.png", :class => "arrow-left" %>
		<%= image_tag "arrow_right.png", :class => "arrow-right" %>
		
		<ul>
			<% @for_sale_item.for_sale_item_images.each do |image| %>
				<li><%= image_tag(image.url) %></li>
			<% end %>
		</ul>
	</div>
	
</section>

<section id="profile">
	<ul id="artists">
		<li><%= link_to (@for_sale_item.designer.name.to_s + " " + @for_sale_item.designer.surname.to_s), { :controller => "designers", :action => "show", :id => @for_sale_item.designer } %></li>
	</ul>
	<p><%= raw @for_sale_item.description %></p>
</section>