config/routes.rb
Estudiuni::Application.routes.draw do
  root :to => 'home#index'
  
  namespace :admin do
    
    get '', :controller => 'admin', :action => 'login'
    get 'admin/login', :controller => 'admin', :action => 'login'
    post 'admin/login', :controller => 'admin', :action => 'login'  
    get 'admin/logout', :controller => 'admin', :action => 'logout'
    
    resources :main
    
    resources :designers
    
    resources :jobs do
      resources :job_images
      get 'job_images/:id/up', :controller => 'job_images', :action => 'up'
      get 'job_images/:id/down', :controller => 'job_images', :action => 'down'
    end
    
    resources :for_sale_items do
      resources :for_sale_item_images
      get 'for_sale_images/:id/up', :controller => 'for_sale_item_images', :action => 'up'
      get 'for_sale_images/:id/down', :controller => 'for_sale_item_images', :action => 'down'
    end
    
  end
  
  get '/about', :controller => 'main', :action => 'about'
  get '/jobs', :controller => 'main', :action => 'jobs'
  
  resources :home, only: [:index]
  resources :for_sale_items
  resources :contacts, only: [:index], :path => 'contact'
  
  get 'locales/:locale', :controller => 'locales', :action => 'set'
  
  get 'designers', :controller => 'designers', :action => 'index'
  get ':id', :controller => 'designers', :action => 'show'
  get ':designer_id/jobs', :controller => 'jobs', :action => 'index'
  get ':designer_id/sale', :controller => 'for_sale_items', :action => 'index'
  #get ':designer_id/jobs/:id', :controller => 'jobs', :action => 'show'
  
  get 'sale/:id', :controller => 'for_sale_items', :action => 'show'
  #get ':designer_id/shop/:id', :controller => 'jobs', :action => 'show'
  
  resources :jobs
  resources :designers
  resources :for_sale_items
  
end

app/models/job_image.rb
class JobImage < ActiveRecord::Base
  mount_uploader :url, JobImageUploader
  
  default_scope :order => "position ASC"
  
  attr_accessible :url, :job_id
  
  belongs_to :job
  
  def self.consolidate_positions(job_id)
    images = JobImage.where("job_id = ?", job_id)
    position = 0
    images.each do |image|
      image.position = position
      image.save
      position = position + 1
    end    
  
  end
end

app/controllers/admin/job_images_controller.rb
class Admin::JobImagesController < Admin::AdminController
  
  before_filter :authenticate
  
  def index
    JobImage.consolidate_positions( params[:job_id] || params[:job] )
    @job = Job.find( params[:job_id] )
    @job_images = @job.job_images
  end
  
  def new
    @job = Job.find( params[:job_id] )
    @job_image = JobImage.new
    @job_image.job = @job
    
    respond_to do |format|
      format.html #new.html.erb
    end
  end
  
  def create
    @job_image = JobImage.new( params[:job_image] )
    @job_image.save
    
    respond_to do |format|
      if @job_image.save
        format.html { redirect_to(:action => "index", :job_id => @job_image.job.id) }
      else
        format.html { redirect_to(:action => "new") }
      end
    end
  end
  
  def destroy
    job_image = JobImage.find( params[:id] )
    job = job_image.job
    job_image.delete
    
    respond_to do |format|
      format.html { redirect_to(:action => "index", :job_id => job.id) }
    end
  end
  
  def up
    image = JobImage.find(params[:id])
    if image.position > 0
      previous_images = JobImage.where("position = ? and job_id = ?", image.position - 1, image.job.id).limit(1)
      if previous_images and previous_images.length > 0
        previous_image = previous_images[0]
        previous_image.position = image.position
        image.position = image.position - 1        
        previous_image.save
        image.save
      end
    end
    
    respond_to do |format|
      format.html { redirect_to(:action => "index", :job_id => image.job.id) }
    end
  end
  
  def down
    image = JobImage.find(params[:id])
    next_images = JobImage.where("position = ? and job_id = ?", image.position + 1, image.job.id).limit(1)
    if next_images and next_images.length > 0
      next_image = next_images[0]
      next_image.position = image.position
      image.position = image.position + 1       
      next_image.save
      image.save
    end
    
    respond_to do |format|
      format.html { redirect_to(:action => "index", :job_id => image.job.id) }
    end
  end
end

app/helpers/admin/job_images_helper.rb
module Admin::JobImagesHelper
end

app/views/admin/job_images/_form.html.erb
<%= form_for [:admin, @job, @job_image] do |f| %>
	<% if @job_image.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@job_image.errors.count, "error") %> prohibited this job from being saved:</h2>
			
			<ul>
				<% @job_image.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<%= f.hidden_field :job_id %>
	
	<div class="field">
		<%= f.label "Imagem" %><br />
		<%= f.file_field :url %>
	</div>
	
	<div class="action">
		<%= f.submit @submit_text %>
	</div>
	
<% end %>

app/views/admin/job_images/index.html.erb
<%= content_for :sidebar do %>
	<ul class="sideNav">
		<li>
			<%= link_to "Voltar", edit_admin_job_path(@job.id) %>
		</li>
	</ul>
<% end %>

<%= content_for :breadcrumbs do %>
	<h2>
		<%= link_to "Trabalhos", admin_jobs_path %>&raquo;
		<%= link_to @job.name, edit_admin_job_path(@job.id) %>&raquo;
		<a href="#" class="active">Images</a>
	</h2>
<% end %>

<%= link_to "Nova imagem", new_admin_job_job_image_path(@job.id), :class => "button" %>

<table class="admin_content">
	<tr>
		<th class="first">Imagem</th>
		<th></th>
		<th class="last"></th>
	</tr>
	<% isOdd = false %>
	<% @job_images.each do |job_image| %>
		<tr class="<%= isOdd ? "odd" : "" %>">
			<td class="first"><%= image_tag job_image.url.thumb %></td>
			<td>
				<%= link_to "Pra cima", {:action => 'up', :id => job_image, :job_id => job_image.job} %>
				<%= link_to "Pra baixo", {:action => 'down', :id => job_image, :job_id => job_image.job} %>
			</td>
			<td class="last">
				<%= link_to "Deletar", admin_job_job_image_path(job_image.job.id, job_image.id), 
	    			:method => :delete, data: { confirm: 'Você tem certeza de que deseja deletar esta imagem?' } %>
			</td>
		</tr>
	<% isOdd = !isOdd %>
	<% end %>
</table>


<%= link_to "Nova imagem", new_admin_job_job_image_path(@job.id), :class => "button" %>

app/views/admin/job_images/new.html.erb
<%= content_for :breadcrumbs do %>
	<h2>
		<%= link_to "Trabalhos", admin_jobs_path %> &raquo; 
		<%= link_to @job.name, admin_job_path(@job.id) %> &raquo; 
		<%= link_to "Imagens", admin_job_job_images_path(@job.id) %> &raquo; 
		<a href="#" class="active">Nova imagem</a>
	</h2>
<% end %>

<% @submit_text = "Salvar" %>
<%= render "form" %>