config/routes.rb
Estudiuni::Application.routes.draw do
  root :to => 'home#index'
  
  namespace :admin do
    
    get '', :controller => 'admin', :action => 'login'
    get 'admin/login', :controller => 'admin', :action => 'login'
    post 'admin/login', :controller => 'admin', :action => 'login'  
    get 'admin/logout', :controller => 'admin', :action => 'logout'
    
    resources :main
    
    resources :designers
    
    resources :jobs do
      resources :job_images
      get 'job_images/:id/up', :controller => 'job_images', :action => 'up'
      get 'job_images/:id/down', :controller => 'job_images', :action => 'down'
    end
    
    resources :for_sale_items do
      resources :for_sale_item_images
      get 'for_sale_images/:id/up', :controller => 'for_sale_item_images', :action => 'up'
      get 'for_sale_images/:id/down', :controller => 'for_sale_item_images', :action => 'down'
    end
    
  end
  
  get '/about', :controller => 'main', :action => 'about'
  get '/jobs', :controller => 'main', :action => 'jobs'
  
  resources :home, only: [:index]
  resources :for_sale_items
  resources :contacts, only: [:index], :path => 'contact'
  
  get 'locales/:locale', :controller => 'locales', :action => 'set'
  
  get 'designers', :controller => 'designers', :action => 'index'
  get ':id', :controller => 'designers', :action => 'show'
  get ':designer_id/jobs', :controller => 'jobs', :action => 'index'
  get ':designer_id/sale', :controller => 'for_sale_items', :action => 'index'
  #get ':designer_id/jobs/:id', :controller => 'jobs', :action => 'show'
  
  get 'sale/:id', :controller => 'for_sale_items', :action => 'show'
  #get ':designer_id/shop/:id', :controller => 'jobs', :action => 'show'
  
  resources :jobs
  resources :designers
  resources :for_sale_items
  
end

app/models/for_sale_item_image.rb
class ForSaleItemImage < ActiveRecord::Base
  mount_uploader :url, JobImageUploader
  
  default_scope :order => "position ASC"
  
  attr_accessible :url, :for_sale_item_id
  
  belongs_to :for_sale_item
  
  def self.consolidate_positions(for_sale_item_id)
    images = ForSaleItemImage.where("for_sale_item_id = ?", for_sale_item_id)
    position = 0
    images.each do |image|
      image.position = position
      image.save
      position = position + 1
    end    
  end
end

app/controllers/admin/for_sale_item_images_controller.rb
class Admin::ForSaleItemImagesController < Admin::AdminController
  
  before_filter :authenticate
  
  def index
    ForSaleItemImage.consolidate_positions( params[:for_sale_item_id] || params[:for_sale_item] )
    @for_sale_item = ForSaleItem.find( params[:for_sale_item_id] )
    @for_sale_item_images = @for_sale_item.for_sale_item_images
  end
  
  def new
    @for_sale_item = ForSaleItem.find( params[:for_sale_item_id] )
    @for_sale_item_image = ForSaleItemImage.new
    @for_sale_item_image.for_sale_item = @for_sale_item
    
    respond_to do |format|
      format.html #new.html.erb
    end
  end
  
  def create
    @for_sale_item_image = ForSaleItemImage.new( params[:for_sale_item_image] )
    @for_sale_item_image.save
    
    respond_to do |format|
      if @for_sale_item_image.save
        format.html { redirect_to(:action => "index", :for_sale_item_id => @for_sale_item_image.for_sale_item.id) }
      else
        format.html { redirect_to(:action => "new") }
      end
    end
  end
  
  def destroy
    for_sale_item_image = ForSaleItemImage.find( params[:id] )
    for_sale_item = for_sale_item_image.for_sale_item
    for_sale_item_image.delete
    
    respond_to do |format|
      format.html { redirect_to(:action => "index", :for_sale_item_id => for_sale_item.id) }
    end
  end
  
  def up
    image = ForSaleItemImage.find(params[:id])
    if image.position > 0
      previous_images = ForSaleItemImage.where("position = ? and for_sale_item_id = ?", image.position - 1, image.for_sale_item.id).limit(1)
      if previous_images and previous_images.length > 0
        previous_image = previous_images[0]
        previous_image.position = image.position
        image.position = image.position - 1        
        previous_image.save
        image.save
      end
    end
    
    respond_to do |format|
      format.html { redirect_to(:action => "index", :for_sale_item_id => image.for_sale_item.id) }
    end
  end
  
  def down
    image = ForSaleItemImage.find(params[:id])
    next_images = ForSaleItemImage.where("position = ? and for_sale_item_id = ?", image.position + 1, image.for_sale_item.id).limit(1)
    if next_images and next_images.length > 0
      next_image = next_images[0]
      next_image.position = image.position
      image.position = image.position + 1       
      next_image.save
      image.save
    end
    
    respond_to do |format|
      format.html { redirect_to(:action => "index", :for_sale_item_id => image.for_sale_item.id) }
    end
  end
end

app/helpers/admin/for_sale_item_images_helper.rb
module Admin::ForSaleItemImagesHelper
end

app/views/admin/for_sale_item_images/_form.html.erb
<%= form_for [:admin, @for_sale_item, @for_sale_item_image] do |f| %>
	<% if @for_sale_item_image.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@for_sale_item_image.errors.count, "error") %> prohibited this job from being saved:</h2>
			
			<ul>
				<% @for_sale_item_image.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<%= f.hidden_field :for_sale_item_id %>
	
	<div class="field">
		<%= f.label "Imagem" %><br />
		<%= f.file_field :url %>
	</div>
	
	<div class="action">
		<%= f.submit @submit_text %>
	</div>
	
<% end %>

app/views/admin/for_sale_item_images/index.html.erb
<%= content_for :sidebar do %>
	<ul class="sideNav">
		<li>
			<%= link_to "Voltar", edit_admin_for_sale_item_path(@for_sale_item.id) %>
		</li>
	</ul>
<% end %>

<%= content_for :breadcrumbs do %>
	<h2>
		<%= link_to "Trabalhos", admin_for_sale_items_path %>&raquo;
		<%= link_to @for_sale_item.name, edit_admin_for_sale_item_path(@for_sale_item.id) %>&raquo;
		<a href="#" class="active">Images</a>
	</h2>
<% end %>

<%= link_to "Nova imagem", new_admin_for_sale_item_for_sale_item_image_path(@for_sale_item.id), :class => "button" %>

<table class="admin_content">
	<tr>
		<th class="first">Imagem</th>
		<th></th>
		<th class="last"></th>
	</tr>
	<% isOdd = false %>
	<% @for_sale_item_images.each do |for_sale_item_image| %>
		<tr class="<%= isOdd ? "odd" : "" %>">
			<td class="first"><%= image_tag for_sale_item_image.url.thumb %></td>
			<td>
				<%= link_to "Pra cima", {:action => 'up', :id => for_sale_item_image, :for_sale_item_id => for_sale_item_image.for_sale_item} %>
				<%= link_to "Pra baixo", {:action => 'down', :id => for_sale_item_image, :for_sale_item_id => for_sale_item_image.for_sale_item} %>
			</td>
			<td class="last">
				<%= link_to "Deletar", admin_for_sale_item_for_sale_item_image_path(for_sale_item_image.for_sale_item.id, for_sale_item_image.id), 
	    			:method => :delete, data: { confirm: 'Você tem certeza de que deseja deletar esta imagem?' } %>
			</td>
		</tr>
	<% isOdd = !isOdd %>
	<% end %>
</table>


<%= link_to "Nova imagem", new_admin_for_sale_item_for_sale_item_image_path(@for_sale_item.id), :class => "button" %>

app/views/admin/for_sale_item_images/new.html.erb
<%= content_for :breadcrumbs do %>
	<h2>
		<%= link_to "Trabalhos", admin_for_sale_items_path %> &raquo; 
		<%= link_to @for_sale_item.name, admin_for_sale_item_path(@for_sale_item.id) %> &raquo; 
		<%= link_to "Imagens", admin_for_sale_item_for_sale_item_images_path(@for_sale_item.id) %> &raquo; 
		<a href="#" class="active">Nova imagem</a>
	</h2>
<% end %>

<% @submit_text = "Salvar" %>
<%= render "form" %>